sudo: false

language: node_js
node_js:
  - 13

# Fix build failure.
# https://github.com/cypress-io/cypress/issues/4069#issuecomment-488315675
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    # I think it defaults to this:
    - node_modules
    # Default if "npm ci" were the script, but non-empty, so include it explicitly:
    - ~/.npm
    # Cypress binary is here:
    - ~/.cache

script:
  - ./test.sh
